# This configuration was used Ebert to review the kbaird/consensus repository
# on becdcee798f76d07dffb3f600a78e8668b9b8de4.
# You can make this the default configuration for future reviews by moving this
# file to your repository as `.ebert.yml` and pushing it to GitHub, and tweak
# it as you wish - To know more on how to change this file to better review your
# repository you can go to https://ebertapp.io/docs/config and see the configuration
# details.
---
styleguide: plataformatec/linters
engines:
  remark-lint:
    enabled: true
#exclude_paths:
#- README.md

